#pragma once

#define DHEAP_CELL_SIZE (2u * KB)
#define DHEAP_MIN_CELL_SIZE (4u * KB)
#define DHEAP_BLOCK_SIZE (16u * MB)
#define DHEAP_MAX_SIZE (2u * GB)

#define DHEAP_CELL_SIZE_BITS (25)

#define DHEAP_BLOCK_COUNT (DHEAP_MAX_SIZE / DHEAP_BLOCK_SIZE)
#define DHEAP_CELLS_PER_BLOCK (DHEAP_BLOCK_SIZE / DHEAP_CELL_SIZE)
